---
title: "a3_task3_hollie_pennington"
author: "Hollie Pennington"
date: "10/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(ggplot2)
library(kableExtra)
library(lubridate)
library(janitor)
library(plotly)
```

```{r}
urchins <- read_csv(here("data", "urchins.csv")) %>% 
  clean_names
```

#Section 1: Size Comparisons: purple and red urchins 

```{r}
ggplot(data = urchins, aes(x = size)) + #read in data for ggplot
  geom_histogram(bins = 10) + #choose graph sytle and bin number
  facet_wrap(~ common_name) + #faceted by color (common name)
  labs(x = "Urchin Diameter (cm)", title = "Purple VS Red Urchins Size Comparison") #labeled graph 
```
Figure 1: Shows the size in diameter (cm) in sea urchins based on color. 

#Descriptive Statistics Table 

```{r}
urchins_table <- urchins %>% #name table from urchins data
  group_by(common_name) %>%  #group by the common name 
  summarise(mean_size = mean(size, na.rm = TRUE), #find mean 
            sd_size = sd(size, na.rm = TRUE), #find standard deviation
            sample_size = n()) #find sample size 

urchins_table #show table 

urchins_table %>% #let kableExtra know where to pull data from 
  kable(col.names = c("Species", "Mean Diameter (cm)", "Standard Deviation (cm)", "Samlple Size (n)"), caption = "<b> TITLE </b> Insert text") %>% #named columns and added caption
  kable_styling(full_width = FALSE) #fixed width 
```
INSERT TEXT HERE FOR iii

#Section 2

```{r}
purple_urchins <- urchins %>% #created new_named data set
  filter(common_name == "Purple Urchin") %>% #filtered for purple urchins
  mutate(date = mdy(date)) %>% #created date 
  mutate(year = year(date)) %>% # create new column with year 
  mutate(Site = case_when(
    site %in% c("NAPL") ~ "Naples Reef", 
    site %in% c("AQUE") ~ "Arroyo Quemado Reef",
    site %in% c("CARP") ~ "Carpinteria Reef",
    site %in% c("IVEE") ~ "Isla Vista Reef"
  )) #change site names from abbreviations to full names
```

```{r}
purple_urchins_table <- purple_urchins %>% #create new data frame
  group_by(Site, year) %>% #grouped for site and year
  summarize(total = n()) #found total for year and site 
```

```{r}
ggplot(data = purple_urchins_table, aes(x = year, y = total, fill = Site)) +
  geom_col(position = position_dodge(), width = 0.75) + 
  labs(title = "Total Purple Urchins", x = "Year", y = "Number of Urchins") + 
  theme(legend.position = c(0.8, 0.75), 
        legend.key.size = unit(.35, 'cm'))
```
ADD TEXT HERE to explain interpretation 